language: go

before_install:
  - sudo apt-get update
  - sudo apt-get install -y make
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

go:
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - tip
